version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - /Users/henrysilvacastillo/Webs/smtptesting:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000 --reload